import Head from 'next/head';
import TrelloSim from '../page-components/trello';
import '../styles/Home.module.css';

export default function Home() {
	return (
		<div style={{ margin: 16 }}>
			<Head>
				<title>Trello Supr Daily</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<TrelloSim />
			</main>
		</div>
	);
}
